# This is an appspec.yml template file for use with an EC2/On-Premises
# deployment in CodeDeploy.
# For help completing this file, see the "AppSpec File Reference" in the
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
# During the Install deployment lifecycle event (which occurs between the
#   BeforeInstall and AfterInstall events), copy the specified files
#   in "source" starting from the root of the revision's file bundle
#   to "destination" on the Amazon EC2 instance.
# A blank or incomplete "files" section
#   may cause associated deployments to fail.
files:
  - source: /app
    destination: /var/www/html/portfolio/app
  - source: /boostrap
    destination: /var/www/html/portfolio/bootstrap
  - source: /config
    destination: /var/www/html/portfolio/config
  - source: /database
    destination: /var/www/html/portfolio/database
  - source: /public
    destination: /var/www/html/portfolio/public
  - source: /resources
    destination: /var/www/html/portfolio/resources
  - source: /routes
    destination: /var/www/html/portfolio/routes
  - source: /storage
    destination: /var/www/html/portfolio/storage
  - source: /tests
    destination: /var/www/html/portfolio/tests
  - source: /artisan
    destination: /var/www/html/portfolio
  - source: /composer.json
    destination: /var/www/html/portfolio
  - source: /composer.lock
    destination: /var/www/html/portfolio
  - source: /package-lock.json
    destination: /var/www/html/portfolio
  - source: /package.json
    destination: /var/www/html/portfolio
  - source: /README.md
    destination: /var/www/html/portfolio
  - source: /server.php
    destination: /var/www/html/portfolio
  - source: /webpack.mix.js
    destination: /var/www/html/portfolio
# A blank or incomplete "permissions"
#   section may cause associated deployments to fail.
# permissions:
#   - object:
#     pattern:
#     except:
#     owner:
#     group:
#     mode:
#     acls:
#       -
#     context:
#       user:
#       type:
#       range:
#     type:
hooks:
# For each deployment lifecycle event, specify multiple "location" entries
#   if you want to run multiple scripts during that event.
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
# During the BeforeInstall deployment lifecycle event, run the commands
#   in the script specified in "location".
  # BeforeInstall:
  #   - location: scripts/before_install.sh # From scratch dependencies get
                                            # installed here
  #     timeout: 300
  #     runas: root
# During the AfterInstall deployment lifecycle event, run the commands
#   in the script specified in "location".
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root
# During the ApplicationStart deployment lifecycle event, run the commands
#   in the script specified in "location".
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
# During the ValidateService deployment lifecycle event, run the commands
#   in the script specified in "location".
  # ValidateService:
  #   - location:
  #     timeout:
  #     runas:
